---
- hosts: server2
  user: root
  gather_facts: yes
  tasks:
       - name: remove tomcat
         file: path=/usr/local/tomcat state=absent
       - name: download tomcat
         get_url: url=http://redrockdigimark.com/apachemirror/tomcat/tomcat-7/v7.0.73/bin/apache-tomcat-7.0.73.tar.gz dest=/tmp
       - name: extract archive
         unarchive: src=/tmp/apache-tomcat-7.0.73.tar.gz dest=/tmp copy=no
       - name: create tomcat dir
         command: mkdir /usr/local/tomcat
       - name: move tomcat dir
         command: mv /tmp/apache-tomcat-7.0.73 /usr/local/tomcat
       - name: start tomcat
         command: nohup /usr/local/tomcat/apache-tomcat-7.0.73/bin/./startup.sh
